apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: my-mongodb
  namespace: worksolutionsai
spec:
  members: 1
  type: ReplicaSet
  version: 4.4.6
  persistent: true
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: owner
      db: worksolutions
      passwordSecretRef:
        name: mongodb-password
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.cacheSizeGB: 0.25

